title: Machine Coaching And Other Assorted Blog Posts
description: Personal blog
author: Bogdan Budescu
github: https://github.com/bbudescu
about: I am a freelance machine learning engineer, mostly dealing with computers' vision problems
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
#     - icon: fa-facebook
#       link: "#"
#     - icon: fa-twitter
#       link: "https://twitter.com/agusmakmun6"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/bbudescu/"
    - icon: fa-github
      link: "https://github.com/bbudescu"
    - icon: fa-stack-exchange
      link: "https://stackexchange.com/users/2850010/bbudescu"

# share:
#   twitter_username: agusmakmun6
#   fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
#     - text: My Projects
#       url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://bbudescu.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
